# THIS FILE IS USED TO CONFIGURE SHOP DISPLAY NAME TAGS #
# ================================================================== #
# &b : AQUA
# &0 : BLACK
# &9 : BLUE
# &l : BOLD
# &3 : DARK_AQUA
# &1 : DARK_BLUE
# &8 : DARK_GRAY
# &2 : DARK_GREEN
# &5 : DARK_PURPLE
# &4 : DARK_RED
# &6 : GOLD
# &7 : GRAY
# &a : GREEN
# &o : ITALIC
# &d : LIGHT_PURPLE
# &k : MAGIC
# &c : RED
# &r : RESET
# &m : STRIKETHROUGH
# &n : UNDERLINE
# &f : WHITE
# &e : YELLOW

# [item] : The name of the item in the transaction #
# [item amount] : The amount of the item #
# [item type] : The material type of the item in the transaction #
# [barter item] : The name of the barter item in the transaction #
# [barter item amount] : The amount of the barter item #
# [barter item type] : The material type of the barter item in the transaction #
# [price] : The price of the items (adjusted to match virtual or physical currency) #
# [price per item] : The price of 1 individual item (calculated from total price and adjusted to match virtual or physical currency) #
# [stock] : The number of stacks of items that a shop/shop owner is able to provide to other players (calculated)#
# [user] : The name of the player who used the shop #
# [owner] : The name of the shop owner #
# [server name] : The name of the server #
# [shop type] : The type of the shop (sell, buy, barter) #

# [lshift] : shift location of entire nametag left #
# [rshift] : shift location of entire nametag right #

display_tag_text:
   SELL:
      normal:
         - "[item]"
   BUY:
      normal:
         - "[item]"
   BARTER:
      normal:
         - "[lshift][item]"
         - "[rshift][barter item]"
   GAMBLE:
      normal:
         - "[item]"
   COMBO:
      normal:
         - "[item]"